// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYRHQHQkyVv6zg8WRmCcrk7nPkLAAEO8',
    appId: '1:111672034018:web:6f84497389f94b366114bb',
    messagingSenderId: '111672034018',
    projectId: 'speedy-defender-451320-f7',
    authDomain: 'speedy-defender-451320-f7.firebaseapp.com',
    storageBucket: 'speedy-defender-451320-f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlbGY5JmX3zjVVsXoDz85L82P4gpxFiWY',
    appId: '1:111672034018:android:90c60d9e3a0536236114bb',
    messagingSenderId: '111672034018',
    projectId: 'speedy-defender-451320-f7',
    storageBucket: 'speedy-defender-451320-f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp6q68cjIt6oqBUSbsCoylYvyAsHAhfkI',
    appId: '1:111672034018:ios:a5d7df8290b8c6d66114bb',
    messagingSenderId: '111672034018',
    projectId: 'speedy-defender-451320-f7',
    storageBucket: 'speedy-defender-451320-f7.firebasestorage.app',
    iosBundleId: 'com.example.suveydTicaret',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp6q68cjIt6oqBUSbsCoylYvyAsHAhfkI',
    appId: '1:111672034018:ios:a5d7df8290b8c6d66114bb',
    messagingSenderId: '111672034018',
    projectId: 'speedy-defender-451320-f7',
    storageBucket: 'speedy-defender-451320-f7.firebasestorage.app',
    iosBundleId: 'com.example.suveydTicaret',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwYRHQHQkyVv6zg8WRmCcrk7nPkLAAEO8',
    appId: '1:111672034018:web:a272cb98609faeca6114bb',
    messagingSenderId: '111672034018',
    projectId: 'speedy-defender-451320-f7',
    authDomain: 'speedy-defender-451320-f7.firebaseapp.com',
    storageBucket: 'speedy-defender-451320-f7.firebasestorage.app',
  );
}
